
services:
  conteneur_api:
    container_name: conteneur_api
    image: conteneur_api
    build:
      context: .
      dockerfile: conteneur_api/Dockerfile.api
    ports:
      - "8083:8083"
    depends_on:
      postgresdb:
        condition: service_healthy

  conteneur_polls:
    container_name: conteneur_polls
    image: conteneur_polls
    environment:
      - POSTGRES_DB=fisa
      - POSTGRES_USER=fisa
      - POSTGRES_PASSWORD=fisa
      - POSTGRES_HOST=postgresdb
      - POSTGRES_PORT=5432
    build:
      context: .
      dockerfile: conteneur_polls/Dockerfile.front
    ports:
      - "8001:8001"
    depends_on:
      postgresdb:
        condition: service_healthy

  postgresdb:
    container_name: postgresdb
    image: postgres:13
    environment:
      - POSTGRES_DB=fisa
      - POSTGRES_USER=fisa
      - POSTGRES_PASSWORD=fisa
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fisa -d fisa"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
    - postgres_data:/var/lib/postgresql/data  # Persister les données de PostgreSQL
  
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "8081:80"
    depends_on: 
      - conteneur_polls
      - conteneur_api
      - postgresdb
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/access.log:/var/log/nginx/access.log


volumes:
  postgres_data:



