# Generated by Django 5.1 on 2024-09-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classe',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contenu',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='personnage',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='serveur',
            old_name='nom',
            new_name='name',
        ),
    ]
